name: CI and CD with uv

on:
  push:
    branches: [main, master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set Python version
        run: uv python install 3.10

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: |
          echo "No tests yet â€” CI passed"

  deliver:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set Python version
        run: uv python install 3.10

      - name: Install dependencies
        run: uv sync

      - name: Generate data report
        run: uv run python src/generate_report.py

      - name: Verify output
        run: ls -R data

      - name: Upload data report artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-report
          path: data/processed/report_nilai.csv
